### ISSUE TITLE
Rss feed for notebook

### ISSUE THREAD

**Issue by sr320** [RobertsLab/resources#2090]
What is the rss feed for your lab notebook?

**Comment by shedurkin** [comment]
I'm not sure - this is the change you made a few months ago to try adding my notebook to the lab notebook slack channel:

https://github.com/shedurkin/Roberts-LabNotebook/commit/5cbd17666f627716106f7e1b567acac9c4564eba

Where would I locate information on rss feed?

**Comment by shedurkin** [comment]
Doing this in the `index.qmd` file caused some weird formattign on my landing page, so I tried adding `feed: true` to the `listing` section of each of my project header .qmd pages. Not sure whether it worked? I just pushed an update to my daily log page and it didn't show up in the slack. Not sure if the slack feed only shows new files (not changes to existing files) and/or if there's a delay.

**Comment by sr320** [comment]
I think that worked. so you will have rss feed for every page.

eg this page
https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/E5_coral.html 
has rss of
https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/E5_coral.xml

It's still not automatic to slack - I have to engage IFTTT

**Comment by shedurkin** [comment]
I still haven't seen any of my posts on the Slack channel -- have you had the chance to update the back-end portion @sr320

**Comment by sr320** [comment]
Should be online now if you wanna test

**Comment by shedurkin** [comment]
Realized I'm not seeing my Smithsonian notebook posts show up in the RSS feed. I have the appropriate settings in my .qmd yaml, but @sr320 I think you need to do something on your side to have posts show up in the feed? The RSS would be https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/SIFP_2025.xml

**Comment by shedurkin** [comment]
Another RSS feed to add please @sr320 ! My `ceasmallr` work hasn't been showing up in the slack channel -- it's at: [https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/ceasmallr.xml](https://shedurkin.github.io/Roberts-LabNotebook/posts/projects/ceasmallr.xml)
