### ISSUE TITLE
Add RRBS salmon data and WGBS sea lice data to Nightingales?

### ISSUE THREAD

**Issue by shellytrigg** [RobertsLab/resources#713]
@kubu4 can I add the new RRBS salmon data and WGBS sea lice data to Nightingales? I started filling out the metadata for it:

[https://docs.google.com/spreadsheets/d/1LM3-sf1IkK5jFR4Apc0gG73TEB9NOuxF9t9nWjffyu0/edit?usp=sharing](https://docs.google.com/spreadsheets/d/1LM3-sf1IkK5jFR4Apc0gG73TEB9NOuxF9t9nWjffyu0/edit?usp=sharing)

**Comment by kubu4** [comment]
Yea, of course. Anybody can add files to nightingales.

**Comment by shellytrigg** [comment]
@kubu4 is it writable?

(base) ostrich:20190722 strigg$ cd /Volumes/web-1/nightingales/
(base) ostrich:nightingales strigg$ mkdir C_rogercresseyi
mkdir: C_rogercresseyi: Permission denied
(base) ostrich:nightingales strigg$ ls -lh
total 772
drwx------  1 strigg  staff    16K Mar  1  2017 A_elegantissima
drwx------  1 strigg  staff    16K Oct 15  2018 C_bairdi
drwx------@ 1 strigg  staff    16K May  1 12:34 C_gigas
drwx------@ 1 strigg  staff    16K Feb  5  2016 C_pallasii
drwx------  1 strigg  staff    16K Jun 26 15:34 C_virginica
drwx------  1 strigg  staff    16K Jan 22  2018 Geoduck_10x
drwx------  1 strigg  staff    16K Aug  8  2017 Geoduck_HiSeq
drwx------  1 strigg  staff    16K Aug  8  2017 Geoduck_MiSeq
drwx------  1 strigg  staff    16K Sep  1  2017 Geoduck_NovaSeq
drwx------  1 strigg  staff    16K Feb  5  2016 H_cracherodii
drwx------  1 strigg  staff    16K Feb  5  2016 H_kamtschatkana
drwx------  1 strigg  staff    16K Feb  5  2016 M_mercenaria
drwx------@ 1 strigg  staff    16K Feb  5  2016 O_keta
drwx------@ 1 strigg  staff    16K Feb  5  2016 O_kisutch
drwx------  1 strigg  staff    16K Jan 28 14:23 O_lurida
drwx------  1 strigg  staff    16K Apr 12  2017 P_adspersus
drwx------  1 strigg  staff    16K Feb  5  2016 P_flavescens
drwx------  1 strigg  staff    16K Apr  8 14:38 P_generosa
drwx------@ 1 strigg  staff    16K Feb  5  2016 P_helianthoides
drwx------  1 strigg  staff    16K Mar  1  2017 Porites_spp
drwx------  1 strigg  staff    16K Feb  5  2016 QPX
drwx------  1 strigg  staff    16K Feb  5  2016 S_namaycush
drwx------  1 strigg  staff    16K Feb  5  2016 V_philippinarum
drwx------  1 strigg  staff    16K Feb  5  2016 V_tubiashii
-rwx------@ 1 strigg  staff   1.5K Feb  5  2016 ngs_automator.sh

**Comment by kubu4** [comment]
Try `rsync` instead and/or via the web interface.

**Comment by kubu4** [comment]
Whoops! You need to make a directory. Do that via the web interface. Then, you should be able to transfer files via `rsync`.

Also, `rsync` is a better way to transfer files, as it has built-in checksum verification to ensure the data doesn't get corrupted during transfer. Then, you don't necessarily need to verify MD5 checksums after you transfer the files.

**Comment by shellytrigg** [comment]
Got it. Had just tried to make a directory in the terminal and hadn't tried to copy anything because I couldn't make the directory to copy files into. I tried to create a folder on the web interface and got this message:
![Screen Shot 2019-07-22 at 12 38 13 PM](https://user-images.githubusercontent.com/4720221/61659962-aaec1980-ac7d-11e9-93fb-b5196e180635.png)

**Comment by kubu4** [comment]
Sorry about that. OK, I just created that folder. Try `rsync`-ing files now.

**Comment by shellytrigg** [comment]
awesome, thanks! Can you also make a folder for S_salar for the salmon data?

**Comment by kubu4** [comment]
Done!

**Comment by shellytrigg** [comment]
@kubu4 tried rsync-ing 8 files and doesn't seem like anything copied over. Is this still a permissions thing?

![Screen Shot 2019-07-22 at 2 18 42 PM](https://user-images.githubusercontent.com/4720221/61666272-ed1c5780-ac8b-11e9-88d4-ce90af4fb7a1.png)

**Comment by kubu4** [comment]
You need to use `rsync` in "remote" mode. E.g.:

`rsync --archive --progress Sealice* username@owl.fish.washington.edu:/volume1/web/nightingales/C_rogercresseyi`

For some reason, I can never copy (or rsync) files to Owl when it's mounted as a drive. I always have to copy via rsync remotely.

**Comment by shellytrigg** [comment]
I just tried to do the following and still getting error "module is read only"

![Screen Shot 2019-07-22 at 2 30 59 PM](https://user-images.githubusercontent.com/4720221/61666909-7b450d80-ac8d-11e9-98e8-14df93f6f61b.png)

**Comment by kubu4** [comment]
Yeesh. Sorry. Do you have the files on a HDD or did you download them from their server? Basically, can you get me the files and I'll get them transferred?

**Comment by shellytrigg** [comment]
The core shared the data with me via Globus and I downloaded them through that web interface. I downloaded everything onto Gannet here:
[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718_done/](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718_done/)

The compressed tar file is still on Gannet here:
[https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718.tar.gz](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718.tar.gz)

Both salmon and sea lice data are in one folder since everything was sequenced together. 

Based on the data structure on Owl, I thought it made the most sense to store them in separate directories based on their species, but maybe it makes more sense to store the all the data together since the run info is the same for all the data (i.e. [undetermined indices](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718_done/Undetermined_S0_L001_R1_001.fastq.gz), [flow cell reports](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718_done/Reports/), and [flow cell stats](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718_done/Stats/))?

**Comment by kubu4** [comment]
Thanks. I'll get them transferred to the two species folders. Presumably all FastQs that are _not_ labeled "sea lice" are _S.salar_?

Sorry for the hassle!

**Comment by shellytrigg** [comment]
That's correct (except the "Undetermined" fastqs). I added the sample info to the the bottom of the [nightingales data log](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit#gid=0).

**Comment by shellytrigg** [comment]
thanks @kubu4 ! One last question, are you also planning to also copy over the:
- "Undetermined" fastQs
- [flow cell reports](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718_done/Reports/)
- [flow cell stats](https://gannet.fish.washington.edu/metacarcinus/Salmo_Calig/FASTQS/UW_Trigg_190718_done/Stats/)
to each species folder on Nightingales?

I'm not really sure where these files should live but would be good to keep them somewhere. maybe copy to one species directory and in the other species directory just reference them in a readme?

**Comment by kubu4** [comment]
Nope. Just the known FastQs with sequences. You can keep them in your folder on Gannet. I'll mention their location(s) in the readme files on nightingales.

**Comment by sr320** [comment]
@shellytrigg is this complete?

**Comment by shellytrigg** [comment]
@sr320 yes, I just updated the [nightingales log](https://docs.google.com/spreadsheets/d/1_XqIOPVHSBVGscnjzDSWUeRL7HUHXfaHxVzec-I-8Xk/edit#gid=0) with the location info.
